name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run helper scripts to process CSVs
      run: sh datasette/process_csvs.sh
    - name: Build SQLite database
      run: sh datasette/build_db.sh
    - name: Login to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: sh datasette/heroku_deploy.sh
